name: Snyk test for dotnet
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      working-directory: ./backend
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore
        working-directory: ${{env.working-directory}}

      - name: Build
        run: |
          dotnet build --configuration Release --no-restore
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
        working-directory: ${{env.working-directory}}

      - name: Test for vulnerabilities with Snyk
        uses: actions/checkout@v2
      - name: Snyk test
        uses: snyk/actions/dotnet@master
        with:
          args: 'test --severity-threshold=medium'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
